FROM IMAGE as build
ARG app_dns
ARG jupyter_dns
RUN echo "dns name is ${app_dns}"
RUN apt-get -y update 
RUN apt-get -y install sed  
RUN sed -i  "s/APPDNS/${app_dns}/g" /app/.env 
RUN sed -i  "s/JUPYTERDNS/${jupyter_dns}/g" /app/.env && cat /app/.env
RUN npm rebuild node-sass
RUN npm install --silent
RUN npm run build

#prepare nginx
FROM nginx:1.16.0-alpine
COPY --from=build /app/build /usr/share/nginx/html