#encrypt the username and passwd
#echo -n 'postgres' | base64
#echo -n 'postgrespass' | base64
#
--- 
apiVersion: v1
data: 
  password: cG9zdGdyZXNwYXNz 
  username: cG9zdGdyZXM= 
  s3-key-id: QUtJQTRKQVZCQjdJTU01U1NBVjI=
  s3-access-key: dnRaTkVkblljQzgzeGtaV09FUzFpQVZ1V1ZydVEwNkdMTG10MkZMcQ==
  airflow-admin-pass: YWRtaW4=

kind: Secret
metadata: 
  name: mdhcpvservices-v3-5-db-creds
  namespace: mi-v3-5
type: Opaque


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mdhcpvservices-v3-5-pvc
  namespace: mi-v3-5
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mdhcpvservices-v3-5
  namespace: mi-v3-5
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mdhcpvservices-v3-5
  strategy:
      type: RollingUpdate
  template:
    metadata:
      labels:
        app: mdhcpvservices-v3-5
    spec:
      nodeSelector:
         Name: "mi-v3-5"
      imagePullSecrets:
        - name: regcred1
      volumes:
        - name: logs
          persistentVolumeClaim:
             claimName: mdhcpvservices-v3-5-pvc
      hostAliases:
        - ip: "192.168.129.137"
          hostnames:
          - "postgres"
      containers:
        - image: IMAGE
          name: mdhcpvservices-v3-5
          imagePullPolicy: Always
          command: 
          - gunicorn
          - --reload 
          - --bind=0.0.0.0:9090
          - --workers=4 
          - --timeout=3600 
          - app:app
          ports:
          - name: service-port
            containerPort: 9090
          env:
            - name: "APPLICATION_HOST"
              value: "https://mi-preval.mareana.com"
            - name: "API_PG_HOST"
              value: "postgres"
            - name: "API_PG_PORT"
              value: "5432"
            - name: "API_PG_DB"
              value: "mdh"
            - name: "POSTGRES_USER"
              valueFrom:
                secretKeyRef:
                  key: username
                  name: mdhcpvservices-v3-5-db-creds
            - name: "POSTGRES_PASSWORD"
              valueFrom:
                secretKeyRef:
                  key: password
                  name: mdhcpvservices-v3-5-db-creds
            - name: "LOGS"
              value: "/var/log/mdh-cpv-services/"
            - name: "API_VALIDATE_COLUMN_NAMES"
              value: "site:productno:batch_no:parameter:value:test_date:unit:approved"
            - name: "VIEW_API_ENDPOINT"
              value: "https://mi-preval.mareana.com/services/v1/views"
            - name: "CHART_API_ENDPOINT"
              value: "https://mi-preval.mareana.com/services/v1/chart-object"
            - name: "SERVICE_NAME"
              value: "s3"
            - name: "S3_REGION"
              value: "us-east-2"
            - name: "S3_BUCKET_NAME"
              value: "mdhbucket"
            - name: "S3_OBJECT_PATH_DEV"
              value: "mi-dev-service-filesharing-store"
            - name: "S3_KEY_ID"
              valueFrom:
                secretKeyRef:
                  key: s3-key-id
                  name: mdhcpvservices-v3-5-db-creds
            - name: "S3_ACCESS_KEY"
              valueFrom:
                secretKeyRef:
                  key: s3-access-key
                  name: mdhcpvservices-v3-5-db-creds
            - name: "AIRFLOW_DAG_API"
              value: "https://mi-preval.mareana.com/airflow/api/v1/dags/{dag_id}/dagRuns"
            - name: "AIRFLOW_TASK_API"
              value: "https://mi-preval.mareana.com/airflow/api/v1/dags/{dag_id}/dagRuns/{dag_run_id}/taskInstances"
            - name: "AIRFLOW_ADMIN_USER"
              value: "admin"
            - name: "AIRFLOW_ADMIN_PASS"
              valueFrom:
                secretKeyRef:
                  key: airflow-admin-pass
                  name: mdhcpvservices-v3-5-db-creds
          volumeMounts:
            - name: logs
              mountPath: /var/log/mdh-cpv-services/
          resources:
            requests:
              memory: 1Gi
              #  limits:
                  #   cpu: 200m
                  #  memory: 1Gi
---
apiVersion: v1     #service is enabled which is available in cluster , not outside .  Because to discover by the depeendency pods 
kind: Service
metadata:
  name: mdhcpvservices-v3-5
  namespace: mi-v3-5
spec:
  ports:
  - port: 9090
    targetPort: service-port
    protocol: TCP
  selector:
    app: mdhcpvservices-v3-5
  type: ClusterIP
---
apiVersion: autoscaling/v2beta1     # kubectl api-versions  (to check the versions of api w
kind: HorizontalPodAutoscaler
metadata:
  name: mdhcpvservices-v3-5-autoscaler
  namespace: mi-v3-5
spec:
  scaleTargetRef:
          #apiVersion: extensions/v1beta1
    apiVersion: apps/v1
    kind: Deployment
    name: mdhcpvservices-v3-5
  minReplicas: 1
  maxReplicas: 10
  #  targetCPUUtilizationPercentage: 80
  metrics:
          #  - type: Resource
          #resource:
          # name: cpu
          #      targetAverageUtilization: 80
  - type: Resource
    resource:
      name: memory
      # targetAverageValue: 200Mi  not work, changed to below
      targetAverageUtilization: 90


