---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins

---  
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkins-clusterrole
rules:
- apiGroups: ["*"]
  #resources: ["pods","nodes","namespaces","services","deployments","secrets","configmaps","replicasets","horizontalpodautoscalers","pods/log"]
  resources: ["*"]
  verbs: [ "*"]
    #verbs: ["get", "watch", "list","patch","exec","edit","create","describe","logs"]
- apiGroups: ["apps"]
  resources: ["*"]
  verbs: [ "*"]
  # resources: ["pods","nodes","namespaces","services","deployments","secrets","configmaps","replicasets","horizontalpodautoscalers","pods/log"]
  #verbs: ["get", "watch", "list","create","patch","edit","describe","exec","logs"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-clusterrole-binding
subjects:
- kind: User
  name: jenkins
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: jenkins-clusterrole
  apiGroup: rbac.authorization.k8s.io
