# This file can update the JupyterHub Helm chart's default configuration values.
#
# For reference see the configuration reference and default values, but make
# sure to refer to the Helm chart version of interest to you!
#
# Introduction to YAML:     https://www.youtube.com/watch?v=cdLNKUoMc6c
# Chart config reference:   https://zero-to-jupyterhub.readthedocs.io/en/stable/resources/reference.html
# Chart default values:     https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/HEAD/jupyterhub/values.yaml
# Available chart versions: https://jupyterhub.github.io/helm-chart/
hub:
  service:
    type: ClusterIP
    annotations: {}
    ports:
      nodePort:
    extraPorts: []
    loadBalancerIP:
  baseUrl: /jupyterhub
  nodeSelector:
    Name: "jupyterhub"
  config:
    AzureAdOAuthenticator:
      client_id: 1a0910db-ecc9-4a00-b42a-8a8554736c4d
      #below is the client secret value not the secret ID
      client_secret: aXO8Q~tj2uBDoC6SQJm7Lp8MC-ojseRPBdjIfbHh
      oauth_callback_url: https://mi-preval.mareana.com/jupyterhub/hub/oauth_callback
      tenant_id: d19e3014-dc30-4e35-ac09-4a8b08d2e688
    Authenticator:
      admin_users:
        - sayed.bakash@mareana.com
        - nagaraju@mareana.com
        - ramakant.sinha@mareana.com
        - dinesh.jinjala@mareana.com
        - ramaa.rao@mareana.com
      auto_login: true
    JupyterHub:
      authenticator_class: azuread
  db:
    type: sqlite-pvc
    upgrade:
    pvc:
      annotations: {}
      selector: {}
      accessModes:
        - ReadWriteOnce
      storage: 1Gi
      subPath:
      storageClassName: gp2
proxy:
  service:
    type: NodePort
singleuser:
  defaultUrl: "/lab"
  extraEnv:
    JUPYTERHUB_SINGLEUSER_APP: "jupyter_server.serverapp.ServerApp"
    INPUT_URL: "jdbc:postgresql://192.168.129.137:5432/mdh"
    OUTPUT_URL: "jdbc:postgresql://192.168.129.137:5432/mdh"
    DRIVER: "org.postgresql.Driver"
    INPUT_USERNAME: "postgres"
    INPUT_PASSWORD: "postgrespass"
    OUTPUT_USERNAME: "postgres"
    OUTPUT_PASSWORD: "postgrespass"
    SQLALCHEMY_INPUT: "postgresql+psycopg2://postgres:postgrespass@192.168.129.137:5432/mdh?client_encoding=utf8'"
    SQLALCHEMY_OUTPUT: "postgresql+psycopg2://postgres:postgrespass@192.168.129.137:5432/mdh?client_encoding=utf8'"
    PSYCOPG_PARAMS: "host='192.168.129.137' dbname=mdh user=postgres password='postgrespass'"
    URL: "bolt://192.168.132.176:7687"
    USERNAME: "neo4j"
    PASSWORD: "Mareana@190"
    GRAPHDB_API: "http://graphdb-api-v3-5.mi-v3-5.svc.cluster.local:5000/v1/"
  image:
    name: IMAGE 
    tag: TAG
    pullPolicy: Always
    pullSecrets: 
        - regcred1
  lifecycleHooks:
    postStart:
      exec:
        command:
          - "sh"
          - "-c"
          - >
             cp -r /tmp/* /home/jovyan/
  storage:
    dynamic:
      storageClass: gp2
  nodeSelector: 
    Name: "jupyterhub"
